apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redirect-sensei
  namespace: argocd
spec:
  destination:
    namespace: director
    name: in-cluster
  project: default
  sources:
    - repoURL: 'https://github.com/phamidko/aks-argocd.git'
      path: aks-staging
      targetRevision: 'master'
      ref: values
    - repoURL: 'carestreamdental.azurecr.io/helm'
      path: 'sensei-redirect'
      targetRevision: 0.1.0
      chart: sensei-redirect
      helm:
          valueFiles:
            - $values/aks-staging/director/sensei-redirect-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2      