apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: director-sensei-frontend
  namespace: argocd
spec:
  destination:
    namespace: director
    name: in-cluster
  project: default
  sources:
    - repoURL: 'https://github.com/phamidko/aks-argocd.git'
      path: 'aks-staging/director'
      targetRevision: 'master'
      ref: values

    - repoURL: 'carestreamdental.azurecr.io/helm'
      path: 'sensei-frontend'
      #helm inspect chart oci://carestreamdental.azurecr.io/helm/sensei-frontend
      targetRevision: 0.1.3
      chart: sensei-frontend
      helm:
          valueFiles:
            - $values/aks-staging/director/sensei-frontend-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true