apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: athena-sensei-frontend
  namespace: argocd
spec:
  destination:
    namespace: athena
    name: in-cluster
  project: default
  sources:
    - repoURL: 'https://github.com/phamidko/aks-argocd.git'
      path: aks-staging
      targetRevision: 'master'
      ref: values

    - repoURL: 'carestreamdental.azurecr.io/helm'
      path: 'sensei-frontend'
      #helm inspect chart oci://carestreamdental.azurecr.io/helm/sensei-frontend
      targetRevision: 0.1.3
      chart: sensei-frontend
      helm:
          valueFiles:
            - $values/aks-staging/athena/sensei-frontend-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2